### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by zxmydmug** [DGP-Studio/Snap.Genshin.Docs#14]
可以把之前的那个天赋书和材料在星期几和什么角色的改回去吗
现在就不大清楚什么材料是什么时候的
还有更新日志里的1600纠缠之缘是什么

**Comment by Masterain98** [comment]
> 可以把之前的那个天赋书和材料在星期几和什么角色的改回去吗
> 现在就不大清楚什么材料是什么时候的
建议已经收到，会考虑以更适当的方式显示


> 还有更新日志里的1600纠缠之缘是什么
Happy April Fools Day
